---
label: about_page_config
hide_body: false
fields:
- name: instagram_link
  type: text
  config:
    required: false
  label: instagram link
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
pages:
- config/about_page.json
