---
label: about_page_config
hide_body: false
fields:
- name: instagram_link
  type: text
  config:
    required: false
  label: instagram link
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: description
- name: grid_config
  type: blocks
  label: grid config
  template_types:
  - home-page-tile
  - home_page_quote
  config:
    min: 
    max: 
pages:
- config/about_page.json
