---
label: home_page_config
hide_body: true
fields:
- name: intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: intro
- name: grid_config
  type: blocks
  label: grid_config
  template_types:
  - home-page-tile
  - home_page_quote
  config:
    min: 
    max: 
pages:
- config/home_page.json
