---
label: home_page_config
hide_body: true
fields:
- name: intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html
  label: intro
pages:
- config/home_page.json